version: "3.8"
services:
  postgresql:
    image: 'postgres'
    restart: on-failure
    hostname: postgrehost
    volumes:
      - postgresql:/data/db
    env_file:
      - ./env/postgresql.env

  mongodb:
    image: 'mongo'
    restart: on-failure
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env

volumes:
  postgresql:
  data:
