version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./rabbitmq.env
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'

